
# cargo-vet audits file

[[audits.assert_tv]]
who = "Amin Faez <amin.faez.inbox@gmail.com>"
criteria = "safe-to-deploy"
version = "0.5.1"

[[audits.assert_tv]]
who = "Amin Faez <amin.faez.inbox@gmail.com>"
criteria = "safe-to-deploy"
version = "0.5.1"

[[audits.assert_tv_macros]]
who = "Amin Faez <amin.faez.inbox@gmail.com>"
criteria = "safe-to-run"
version = "0.5.1"

[[audits.ryu]]
who = "Amin Faez <amin.faez.inbox@gmail.com>"
criteria = "safe-to-deploy"
version = "1.0.10"

[[audits.serde_json]]
who = "Amin Faez <amin.faez.inbox@gmail.com>"
criteria = "safe-to-deploy"
version = "1.0.138"
