[[entries]]
entry_type = "Const"
description = "test setup: peer a secret key"
name = "peer_a_sk"
code_location = "rosenpass/tests/test_vector_crypto_server.rs:125"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:39"
offload = true

[[entries]]
entry_type = "Const"
description = "test setup: peer a public key"
name = "peer_a_pk"
code_location = "rosenpass/tests/test_vector_crypto_server.rs:126"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:39"
offload = true

[[entries]]
entry_type = "Const"
description = "test setup: peer b secret key"
name = "peer_b_sk"
code_location = "rosenpass/tests/test_vector_crypto_server.rs:131"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:39"
offload = true

[[entries]]
entry_type = "Const"
description = "test setup: peer b public key"
name = "peer_b_pk"
code_location = "rosenpass/tests/test_vector_crypto_server.rs:132"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:39"
offload = true

[[entries]]
entry_type = "Const"
description = "pre-shared key"
name = "psk"
value = "AdZKwsLi+FUQZN9XiPjE+P+u4WAVYav0hG14TUlkiJo="
code_location = "rosenpass/tests/test_vector_crypto_server.rs:135"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:39"

[[entries]]
entry_type = "Const"
name = "CryptoServer::cookie_secrets[0]"
value = "Olwvgm1PKzBffUqrD83T9A=="
code_location = "rosenpass/tests/test_vector_crypto_server.rs:186"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:89"

[[entries]]
entry_type = "Const"
name = "CryptoServer::cookie_secrets[1]"
value = "XT9L2rv6UKlljhiKadLFLQ=="
code_location = "rosenpass/tests/test_vector_crypto_server.rs:191"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:89"

[[entries]]
entry_type = "Const"
name = "CryptoServer::biscuit_keys[0]"
value = "2yuSkY5MqvuBMD575QwtJW8S3te5sso2kr9IhVz/EE4="
code_location = "rosenpass/tests/test_vector_crypto_server.rs:196"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:89"

[[entries]]
entry_type = "Const"
name = "CryptoServer::biscuit_keys[1]"
value = "aTSqvHTH3xNda6vXSyWuFyZbAQ+g0Fi1UEoy0nSa/Kw="
code_location = "rosenpass/tests/test_vector_crypto_server.rs:201"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:89"

[[entries]]
entry_type = "Const"
name = "CryptoServer::cookie_secrets[0]"
value = "nH1vRHYcq8U5oJGfhbb6zA=="
code_location = "rosenpass/tests/test_vector_crypto_server.rs:186"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:89"

[[entries]]
entry_type = "Const"
name = "CryptoServer::cookie_secrets[1]"
value = "8d6/NTNmc8YjIxCVEqT1wg=="
code_location = "rosenpass/tests/test_vector_crypto_server.rs:191"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:89"

[[entries]]
entry_type = "Const"
name = "CryptoServer::biscuit_keys[0]"
value = "MqQy1de2KRix8mhdCOxK0badKcuwEPQ8KEL4SpYpTrY="
code_location = "rosenpass/tests/test_vector_crypto_server.rs:196"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:89"

[[entries]]
entry_type = "Const"
name = "CryptoServer::biscuit_keys[1]"
value = "0P8xJhQuQTdvJl9rcqmZLq4ZJ0pz/EMiBHLZsE+sH+k="
code_location = "rosenpass/tests/test_vector_crypto_server.rs:201"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:89"

[[entries]]
entry_type = "Const"
name = "hs.cookie_value.value"
value = "SHo7Q9trkAYxnljPJLTI0w=="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3443"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Const"
name = "hs.core.sidi"
value = "n3PNIA=="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3453"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Const"
name = "hs.eski"
value = "KIs3Z2F7pdZoU0GHRWZUs1grBeh7uSsb+LjAd+oz1BJy1awtW8xdWgE4jXGHxGk9yjO61AxNqVoqaxg1vmKxwoNBTYAVEVquAhOxCuWDCQGnqwZPzSa+MpUj4liaYlCSCoV17BqFdrOtdPqE/NqSBIgOimtVOfxxPnvM9Scm+2NzQFmiYjq7yAtNJtHGX+g2UqO6MhLAa5C/0Xkp1qyFCYZYUDZ0mkNOodfGJcnJGGmCAOKaoKub3pCyHxxCkSAvWCgFEtUEuOeWNRBWVgbEmGY/8Qg+YsFovbKE4TLJwIoGbKcvstVLVePFjGNzBfIyMyxStDZPHmXJbkxt7yx70rlV+ku3oHgoXAmfIDk087YcE7NAbYyAJEGGgdYVFmBh+PgjQMwQ5sLGEvuTW4s59SRm/OKkOag7v2EZQ/uTeappQ6pyALFr7CEDmRtRxlFjg7VRtpRSzLNTYwpUWhzD/khVMJZWW/awbVqPyvoYDLpSgawIreMVL+uDqbGqvdJDfTKb4QpllRAVUbIgNLZtPOgBinpWHow4PelzB3Gwu4wAuLcnM8cC9mOBRWtVTCMdNoGWdigucFyP1Hm01nxoEUV1I8ExJmct5NOphXAcsNuq6OyRD9Ys7cFcm4HITKmjywpMwQaeg5lBISxWOKi4YIwycNAJa1JbyWJYrEkVQ0aTlITMGSac0CCSnAw5uCpJmte1h3FLI+O29LF6MUm/szJR4RfJZAAXA3EZswBWS7ucLcidOpg43GYcJqJ02CqS5BKGl0sqsjmP/vIPFGALuYwuWxMk1mBXCBaWlSVe2sESF2u7+PKwH7WDLRHKobUwYaXB/ykQuxlyxqV7gslJTse3v5k0fKdswcQtQZyNS8dFFZCRdyJRMqWfw8xf4ctJGuavRio2FUJ2DCa3MAS5CdCuI/ty0EgXOnegt8w4XtewfhVFUtSUGqCGkQkpjyUfCXlxmMxMcUWzfpU5f6eDt2E4W/lNc3t0wtuR91h8MQVCFVx5KFF6wcnPvEWZLIU6r6LKNds0Hfm7c8qZVQzQ77lsPih3v5VbNWXDuSgpmRCDMxC1Fmi18fy9L+Jl1mEo+jdkBtcnqUqZY1eDHSC7e/RXbXuGlfuxZSQE9XkvLVRaREdXwMFUMVm1jTjAm9yErpZSBjh95TENlzioOlVKOZWc7NuN7smg8dI5BmmWMRQOuSGbmKNO0yJdslMr5MhkK2C4mLzCIvO5E8klnsNLtAkGc0MLJ2hLKKKofkTMSci7KIaeq/k7BdcjAfAxVwjMtmCMUhEY6cZu83QHUQevb8RBTPh1fnu1mMC0D8p9AYMzNWewyCVe/exABidKmKwm7mMXKetwayyAocFrIyIwEDtP2RNlnBe/M9ZPZqnMbLCabUISm3dZFAG8FasQZ6lLldKyHMmDQ0l75awku8S5xPirVlIyEoq93xUcntEsfMkjxQgNDQcKW3y3ttAiP/u7jBjHfgxkoYFIkEBrY8q2Q2DMJIIppTlwyoBw3eoYnxNF1xJUOqXKaqsFW4eoUcILWWJSSVECQzKpqdoqiREfNeHIVCBE0oyszzF6EwzMPusd4VjJVfJqZ1ibpfVN/kKJUgYIUqqNOlhUk9tiBZqCodHDMXwmfghRXTqtglKQ0CXDKCA4zLWljqy8rBomePAA9HBme4c5LdXHEVWdLRYt2fVIfClmCCU/kQZXtbWUGRuongmwQ9XOseuqmzyGXGR3i5jGNUwg7NicBxyvy6MQNsRBcRBPEubCHrYL0nRXGYs3HJeL0ZJmHxzBrMl0NNO0FZi2kCIx6/Bx1FMXLbRLg2SvjDZFxZW2iKUVaktxtToN1PQ9P5hjIeyJgmd8G1ZLI7sIHVYDBhlUgLeKg8hotucAHKTKrdC3UDu4P9Yi6my9PRrNaSkr21CNjgVkfCu1lwsWQelqr6zNvKEsfRUzkzVpnaHEMiC18sSKvzl5ghVjbMdZZtN9cqhGDDlmTXGpMHTGanhMjgN5l4Nzjryx6VI7fLq8YNeJg/IsJkjEvHp6yiRRp4UA1Ddg6NQ/CzyuXxzAoOBbvFggGxReF3JZW4h5CEEkyv+07+hNkEdGd8Q5bYjcYqxPsz2zRIsPihgO/znebcgWrSHUX4Eqv12DSFqsfOeGMeNdMCz7iF98pRjR6v3rzdfFQr101kjph3Mt"
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3460"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Const"
name = "hs.core.ck"
value = "r6LKNds0Hfm7c8qZVQzQ77lsPih3v5VbNWXDuSgpmRCDMxC1Fmi18fy9L+Jl1mEo+jdkBtcnqUqZY1eDHSC7e/RXbXuGlfuxZSQE9XkvLVRaREdXwMFUMVm1jTjAm9yErpZSBjh95TENlzioOlVKOZWc7NuN7smg8dI5BmmWMRQOuSGbmKNO0yJdslMr5MhkK2C4mLzCIvO5E8klnsNLtAkGc0MLJ2hLKKKofkTMSci7KIaeq/k7BdcjAfAxVwjMtmCMUhEY6cZu83QHUQevb8RBTPh1fnu1mMC0D8p9AYMzNWewyCVe/exABidKmKwm7mMXKetwayyAocFrIyIwEDtP2RNlnBe/M9ZPZqnMbLCabUISm3dZFAG8FasQZ6lLldKyHMmDQ0l75awku8S5xPirVlIyEoq93xUcntEsfMkjxQgNDQcKW3y3ttAiP/u7jBjHfgxkoYFIkEBrY8q2Q2DMJIIppTlwyoBw3eoYnxNF1xJUOqXKaqsFW4eoUcILWWJSSVECQzKpqdoqiREfNeHIVCBE0oyszzF6EwzMPusd4VjJVfJqZ1ibpfVN/kKJUgYIUqqNOlhUk9tiBZqCodHDMXwmfghRXTqtglKQ0CXDKCA4zLWljqy8rBomePAA9HBme4c5LdXHEVWdLRYt2fVIfClmCCU/kQZXtbWUGRuongmwQ9XOseuqmzyGXGR3i5jGNUwg7NicBxyvy6MQNsRBcRBPEubCHrYL0nRXGYs3HJeL0ZJmHxzBrMl0NNO0FZi2kCIx6/Bx1FMXLbRLg2SvjDZFxZW2iKUVaktxtToN1PQ9P5hjIeyJgmd8G1ZLI7sIHVYDBhlUgLeKg8hotucAHKTKrdC3UDu4P9Yi6my9PRrNaSkr21CNjgVkfCu1lwsWQelqr6zNvKEsfRUzkzVpnaHEMiC18sSKvzl5ghVjbMdZZtN9cqhGDDlmTXGpMHTGanhMjgN5l4Nzjryx6VI7fLq8YNeJg/IsJkjEvHp6yiRRp4UA1Ddg6NQ/CzyuXxzAoOBbvFggGxReF3JZW4h5CEEkyv+07+hNkEdGd8Q="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3461"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Output"
name = "hs.core.ck 1"
value = "Baf9U4s/LHJJC6TZ8MgRFQVjKiVDagp7FqLlMAM+Bw4="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3468"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Const"
value = "axO2YA4OIAk4Fq83PKHWTXqs4VV9AyjDt3B7adShX0A="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3184"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:14"

[[entries]]
entry_type = "Const"
value = "OsUb7+brOzJlHFZ8Tosxcs1clcQmMaD7rZOk1H7PPiC+LiGM8xXXsL6qO9tTMtzCbeZqFzC0m9sdfI+eJiKRFM2+09SimHLu9xO5zOg8mB29AW9peYsIi2CictgP1ZIxm985174hTi6fdCqomZVY4XD7HDdGyyUFijJaYmfJE5XjKjZaMpMlkmI0bgK5g5At5zbd6tPmIqHn8RpY"
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3185"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:14"

[[entries]]
entry_type = "Output"
name = "hs.core.ck 2"
value = "1lH4DZf3bSP5M4TIwu5RpWUdWg8MABI8MOl85uevraA="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3476"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Output"
name = "ih.pidic"
value = "D+KrC7LHgVD7t3MVjwL1D+nkQBWQZIG5zNgo299j7fhOAAqdxtpec6FAwAp1ryJ/"
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3487"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Output"
name = "hs.core.ck 3"
value = "RNqz3hZleMoEkyV3jm1Y8cT7gilwI/F18eCYCt2iJ20="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3490"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Output"
name = "hs.core.ck 4"
value = "qap+P5JS8mLH+IYO8YytnjkiMetH1KytbmBwICr9MZ4="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3501"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Output"
name = "ih.auth"
value = "uzbPLbOOMYJ531pUcN9A8Q=="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3510"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Output"
name = "hs.core.ck 5"
value = "7HGBn5+JTSMiW4KQ/WhgtVKolhOYi6YbYmv0lhi3hHY="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3514"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:39"

[[entries]]
entry_type = "Output"
description = "message exchanged by the protocol parties"
name = "message"
code_location = "rosenpass/tests/test_vector_crypto_server.rs:157"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:39"
offload = true

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr IHR 4"
value = "Baf9U4s/LHJJC6TZ8MgRFQVjKiVDagp7FqLlMAM+Bw4="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3551"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr IHR 5"
value = "1lH4DZf3bSP5M4TIwu5RpWUdWg8MABI8MOl85uevraA="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3558"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr IHR 6"
value = "RNqz3hZleMoEkyV3jm1Y8cT7gilwI/F18eCYCt2iJ20="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3568"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr IHR 7"
value = "qap+P5JS8mLH+IYO8YytnjkiMetH1KytbmBwICr9MZ4="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3576"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr IHR 8"
value = "7HGBn5+JTSMiW4KQ/WhgtVKolhOYi6YbYmv0lhi3hHY="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3583"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Const"
name = "session_id"
value = "mKiMlA=="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3589"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr RHR 3"
value = "WhKTwDAlYcZOUK/KocplZiORVtcgaZJM8Pj+c72f6vo="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3597"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Const"
value = "dSvukgVwX8xkBeZw8wzSw7D1XiPapwS48OVfdV5cxQI="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3184"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:14"

[[entries]]
entry_type = "Const"
value = "dl+pS4AKr2h4Fid+alNFmqQb1EvJK7p4Onq8ExfTf+SKbb8ovwSgTQA5v/EayL8quTqTqkI5Jmi3LsPKObbMbKboM0JM/kpLF36/8m8dcwEIDrLdTZWyYfzbRaqOUWt9yf58pujAdWINN5BVGGP1qEknezMibbPH4pUDFL6QB+OnC1FVJGVdo8WKDZzd0jFCgP5UmUPtfQHWXI/1kxK2ip9Ywcnq7tHfEOi2dMd8XIfbL40PpTXMIwE/U4SZdN0aGmhFBVBGWmQe7M1L+UJh4LTdXHFDsXWG/MJ1H1IelV8ZYyUTsrvAAj6e8Flkkfb5IeX/eW5L5fI/qycmeKzyCF3Pz4+7v+tHdnh6yOcjdHS+JB1rCmjSs2ls9DJJFouWykHuNSINpdEAVacl47CyU/k8wXehqK33UsHCBc3+jlP1G9wRhM2sLBYS+A2HSTHf2CxNarfABIDaZDbBg/lK2LEWZhXllUcgzBVAgfFkwGN2WszGmez8C5bBjoplcvaOZdmSi1us1UeyL7C89ZT9YIzEmRQAfz8iS1JFlWWltEnlz81D4xd2/qbQaET2oxHFFdli+S5HBYZuGZ0V/IYzrRY5mr9H4nE831HF0UrS1yLDIUsYKIMt9y0Ge/YJD1lCeiiPWG7Sy1EvIYDK0lYNCiCpTVAWgLTo9VT6eiQYnV9seHRba8P8Taplu2QZAexjsIBjGD7U8+gtBzvNHzJs63xhsjJ1V3FBPaf+iZs4PcBT8pnx2aZdkJVMQHqPn7FaVkVcL9r3fsZdt7KG6WQvvDxvuejQlIjB7pPcy5lrKaE3gSKCo7L9FxsS56kz0++hufb77ezJwr5sygurNzWn7KH6uVAk44NETv8G5jAYxSjKNnubwKL0HS70qHNzcDzS0S/EwsMxKkgHQny9/8qX4BHxy+Q4UEFYK0lVgwjdDi8zcwLE2vKb1s2fU5qqII2fCMdAKVOkxjR2s/binUTvc15TSiKgr+zqqw2bgvViV0we2nlOtaVIHmFV4JEtUw8o"
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3185"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:14"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr RHR 4"
value = "YnhLv1JO/dYJ0Glrnwlgv3g1n2O0NXMM5wLL03h3GyU="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3604"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Const"
value = "njzlPPMAeXwqc3P/F9j89DUEVtrQvH91qWR6iBrK1h0="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3184"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:14"

[[entries]]
entry_type = "Const"
value = "VWQsLv6et4atxhT/EjVsu13fsE5143qaemLLsFn8t8N72wDBOjOhZohXswRO5NlzU9Fx19SM2dzFGbaVQ39BFubYxpoaloRTuDhkUcp+t3833oxo2T2TCl6PyUcM8OpJIs1b+AFjN553f+GJE8lXj8Xh+KXZh5dIbTn6O4Kn3Yauc6bq7ceZhwDDoW369acg86ctljwWq0FvJJHD"
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3185"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:14"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr RHR 5"
value = "0nnN/EyMx89jJZ13H+WlcYu+B96Tc1JUI0EbnL3wrl4="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3612"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Output"
value = "rr2UaW5KMBYhnhpbKlS5BX8YonklHzrs5pFWF0JZZFgBAAAAAAAAAAAAAADSec38TIzHz2MlnXcf5aVxi74H3pNzUlQjQRucvfCuXg=="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3238"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:24"

[[entries]]
entry_type = "Const"
description = "Biscuit key after being cycled"
name = "CryptoServer::biscuit_key[r]"
value = "fPMasxqOZTQ9V9NWMfpeoYu1oOb31nJSR/CEtMO47Yc="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:1422"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:169"

[[entries]]
entry_type = "Const"
value = "2xKQTMcdnpNP/jr7R3JHDLtMQTdi3o9B"
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3255"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:24"

[[entries]]
entry_type = "Output"
value = "2xKQTMcdnpNP/jr7R3JHDLtMQTdi3o9BBuAWtx1UBOvoZKny2FRqE9sTYUWqCVadhQShJxLY8vQJ04d2JJyrfRLwX47lBk820uH5+aHcPBSNacp8UKeueumgVuTZaWtNsRZTUiPZfS67wGkI62PjF92PbAk="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3263"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:24"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr RHR 6"
value = "kzRYw/vrXPOnGaGdfKZb4lOOfhLxlMifIPtzUWL1IB0="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3619"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr RHR 7"
value = "SMKfcUH38KBZA6FANmWTyqsCmcIYKGWAZzXpOpmMW2s="
code_location = "/home/amin/repos/rp/rp_test_vec_v2/rosenpass/src/protocol/protocol.rs:3626"
test_vec_set_code_location = "rosenpass/src/test_vector_sets.rs:100"

[[entries]]
entry_type = "Output"
description = "message exchanged by the protocol parties"
name = "message"
code_location = "rosenpass/tests/test_vector_crypto_server.rs:157"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:39"
offload = true

[[entries]]
entry_type = "Output"
description = "message exchanged by the protocol parties"
name = "message"
code_location = "rosenpass/tests/test_vector_crypto_server.rs:157"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:39"
offload = true

[[entries]]
entry_type = "Output"
description = "message exchanged by the protocol parties"
name = "message"
code_location = "rosenpass/tests/test_vector_crypto_server.rs:157"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:39"
offload = true

[[entries]]
entry_type = "Output"
description = "final exchanged key"
name = "exchanged_key"
value = "N7cf7nvP6+HZqrD+yohH7z+WorXkDqEeGij4D5R/bg0="
code_location = "rosenpass/tests/test_vector_crypto_server.rs:173"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:39"
